name: Test Hatch ğŸ package

on: [pull_request]

jobs:
  build-and-test:
    name: Build and test Hatch package ğŸ
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Hatch
        uses: pypa/hatch@install
      
      - name: Run hatch tests
        run: hatch test

      - name: Run hatch build
        run: hatch build
